version: "3"

tasks:
  generate:
    aliases:
      - migrate
    desc: "Make migrations from migrations directory"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations