// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_postgres

type App struct {
	ID     int32
	Name   string
	Secret string
}

type User struct {
	ID       int32
	Email    string
	PassHash string
}
