// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc_postgres

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(email, pass_hash)
VALUES($1, $2)
RETURNING id
`

type CreateUserParams struct {
	Email    string
	PassHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PassHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getApp = `-- name: GetApp :one
SELECT id, name, secret
FROM apps
WHERE id = $1
`

func (q *Queries) GetApp(ctx context.Context, id int32) (*App, error) {
	row := q.db.QueryRow(ctx, getApp, id)
	var i App
	err := row.Scan(&i.ID, &i.Name, &i.Secret)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, pass_hash
FROM users
WHERE email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PassHash)
	return &i, err
}
