// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_postgres

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (int32, error)
	GetApp(ctx context.Context, id int32) (*App, error)
	GetUser(ctx context.Context, email string) (*User, error)
}

var _ Querier = (*Queries)(nil)
